# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2b03057f59ed7827859ff4a772f771d5ec9e624f248fb72b7209db637606b3948fc316017bbdd2bba62d7199f955fb957d2f1123add0a1a47ad835a89c9e44a0

test:
  secret_key_base: 04ed3576012b3b5624074e43cc32fa27c7cdde1b9b44ef2f86ba858899d5c72ab311a0a7ffff7975f674662892a4ae100dea53ac952a8fbc69c48e0b7a9f3fc7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
